apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/alias1.update-strategy: digest
    argocd-image-updater.argoproj.io/image-list: alias1=anitha1336/gitops-demo:0.3
    argocd-image-updater.argoproj.io/write-back-method: git
  name: demo-app-with-imgupdater-git
  namespace: argocd
spec:
  destination:
    namespace: demo-app-with-imgupdater-git
    server: https://kubernetes.default.svc
  source:
    kustomize:
      images:
      - anitha1336/gitops-demo
    path: demo-app/
    repoURL: https://github.com/anithapriyanatarajan/demogitops-k8-manifests.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
